name: Intall Script
on:
  pull_request:   # körs när någon öppnar eller uppdaterar en pull request
    branches:
      - main
      - Development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # eller den version du använder

      - name: View working directory
        run: dir
        working-directory: ./Backend

      - name: Install dependencies
        run: npm install
        working-directory: C:\Chas\SUVx24\Project Team 9\package.json

      - name: Run ESLint
        run: npx eslint . --max-warnings=0
        working-directory: C:\Chas\SUVx24\Project Team 9\package.json

